### ISSUE TITLE
original add adds twice?

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#10]
after an install...

c:\installs\Ruby18\lib\ruby\gems\1.8\gems\RedCloth-4.2.2\ext\redcloth_scan>pik add
creating C:\Users\Home/.pik
Adding:  186: ruby 1.8.6 (2009-2-27 mbari 8A/0x8770 on patchlevel 287) [i386-mingw32]'
 Located at:  c:/installs/ruby18/bin
Adding:  186: ruby 1.8.6 (2009-2-27 mbari 8A/0x8770 on patchlevel 287) [i386-mingw32]'
 Located at:  c:/installs/ruby18/bin

?

**Comment by vertiginous** [comment]
This is a feature ;-)  It adds the current ruby version by default the first time you run pik, regardless of the command.  It shouldn't actually add it to the config twice.   I'll update the readme to clarify this.

**Comment by vertiginous** [comment]
This behavior has changed.  pik add will only add the current version once, and the current version won't be added by default (you have to run pik add).

Also, if you try to add the same version more than once, you'll be told it's already been added.
