### ISSUE TITLE
allows you to add the same version twice?

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#11]
Dunno if this is something worth caring about, but currently

c:\installs>pik add ruby191\bin
Adding:  191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]'
 Located at:  c:/installs/ruby191/bin

c:\installs>pik add ruby191\bin
Adding:  191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]'
 Located at:  c:/installs/ruby191/bin

c:\installs>pik ls

191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]

191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mswin32]

Thanks!

**Comment by vertiginous** [comment]
I can see a use case for having the same version twice.  Maybe for testing compiler optimizations?  

That being said, having the same version string twice _is_ confusing.  I'm not sure if that's worth doing something about.  The config file is easy enough to edit by hand, though.

**Comment by vertiginous** [comment]
Based on the pik ls output, it appears this is a mingw32 version and a mswin32 version.  But adding two completely identical versions wouldn't be possible.

C:\scripts\repo\pik>pik ls
185: ruby 1.8.5 (2006-12-25 patchlevel 12) [i386-mswin32]
186: ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]
186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32] *
191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]
191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]

C:\scripts\repo\pik>pik add c:\ruby\186-p368-mingw32\bin
Adding:  186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32]'
 Located at:  c:/ruby/186-p368-mingw32/bin

C:\scripts\repo\pik>pik add c:\ruby\186-p368-mingw32\bin
Adding:  186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32]'
 Located at:  c:/ruby/186-p368-mingw32/bin

C:\scripts\repo\pik>pik add c:\ruby\186-p368-mingw32\bin
Adding:  186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32]'
 Located at:  c:/ruby/186-p368-mingw32/bin

C:\scripts\repo\pik>pik ls
185: ruby 1.8.5 (2006-12-25 patchlevel 12) [i386-mswin32]
186: ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]
186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32] *
191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]
191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]

Can you verify that?

**Comment by vertiginous** [comment]
Fixed in 0.1.0
