### ISSUE TITLE
Feature: pik list should star the currently selected version

### ISSUE THREAD

**Issue by rpardee** [vertiginous/pik#12]
Like git does when you list branches.

Many thanks!

Roy

**Comment by vertiginous** [comment]
This is already implemented, and will be in the next release.
C:\scripts\repo\pik>bin\pik ls
185: ruby 1.8.5 (2006-12-25 patchlevel 12) [i386-mswin32]
186: ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]
186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32]
191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]
191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32] *

Thanks Roy, and feel free to drop me a line with any problems or suggestions.

**Comment by rpardee** [comment]
Sweetness--thanks!
