### ISSUE TITLE
problem installing gem (failed RDoc...)

### ISSUE THREAD

**Issue by Anjen1** [vertiginous/pik#131]
Hi, pik installed fine using gem install pik from gitbash to WinXP, but the RDoc failed to load properly. see below for console output. I removed all but the first couple lines of the text bit, since it's probably not salient for this purpose...

$ gem install pik
Fetching: pik-0.2.8.gem (100%)

---
-  If you're upgrading from a version <= 0.1.1, you'll want to delete the pik.bat file
  from all of your ruby versions. Gem uninstall should do the trick.
  ----------<snip>------------
  ----------------------------------------------------------------------------

Successfully installed pik-0.2.8
1 gem installed
Installing ri documentation for pik-0.2.8...
Installing RDoc documentation for pik-0.2.8...
Could not find main page README.rdoc
Could not find main page README.rdoc
Could not find main page README.rdoc
Could not find main page README.rdoc

I'm sure it doesn't matter for using it, but...

**Comment by luislavena** [comment]
Errors generating rdoc can be ignored. As long it says installed gem foo
successfully.

Sorry for top posting. Sent from mobile.
On Jan 29, 2012 11:41 PM, "Andrew Jenkins" <
reply@reply.github.com>
wrote:

**Comment by Anjen1** [comment]
Thanks luislavena, I figured as much, but I did want to note the behavior so it can be addressed.
