### ISSUE TITLE
Pik Use does nothing, "ruby is not recognized" command after selecting

### ISSUE THREAD

**Issue by indigo0086** [vertiginous/pik#135]
I installed pik 0.3.0.pre via the installer, installed 7-zip then ran the commands

``` BAT
C:\Users\Daniel>pik list
   ruby-1.9.2-p136

C:\Users\Daniel>pik use ruby-1.9.2-p136

C:\Users\Daniel>ruby -v
'ruby' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Daniel>pik info
pik 0.3.0.pre on Microsoft Windows [Version 6.1.7601]
by Gordon Thiesfeld (gthiesfeld@gmail.com)


Pik info will not work unless there is a version of ruby in the path.

You can use pik use to add one.

C:\Users\Daniel>
```

**Comment by luislavena** [comment]
Did you relocate your Ruby 1.9.2 installation?

Can you provide us the value of `PATH` environment variable and also the output of `pik list -v`?

**Comment by indigo0086** [comment]
I did not move the installation, I am using it wherever it was when I did pik install 1.9.2  

``` BAT
C:\Windows\System32>set PATH
Path=C:\pik\;...
```

**Comment by luislavena** [comment]
@indigo0086 for me to help you you need to provide me the _entire_ information I'm asking to you.

You snipping the path to show me just pik doesn't help me figure out if Pik is doing it's job on setting the `PATH` to the directory where Ruby 1.9.2 is installed.

You have also omitted to tell me if that version of Ruby was installed by Pik itself or not, which having the output of `pik list -v` as requested would have helped me.

Please, help me help you.

**Comment by indigo0086** [comment]
output of pik list -v

``` BAT
C:\Windows\System32>pik list -v
   ruby-1.9.2-p136
        version: ruby 1.9.2p136 (2010-12-25) [i386-mingw32]
        path: C:\Users\Daniel\.pik\rubies\ruby-1.9.2-p136\bin
```

As for the path, the ruby bin directory is never set, which is why I'm getting the ruby command not found issue.

**Comment by luislavena** [comment]
> As for the path, the ruby bin directory is never set

You mean the directory is never added to the PATH, ok.

Can you tell me how `pik.bat` looks like (paste it here) and the contents of `C:\Users\Daniel\.pik\pik_run.bat` too?

Also, do you have `HOME` environment variable set on your system?

**Comment by indigo0086** [comment]
After looking at the contents of the bat file I had to set the PIK_HOME variable to get it to work.  I didn't see that in the documentaiton page

**Comment by luislavena** [comment]
See #118, the batch files are not as smart as expected.

Perhaps you can submit a improvement to the README?
