### ISSUE TITLE
Download and install

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#14]
It would be nice to be able to run something like:
    pik install ruby 186

or 

```
pik install ironruby
```

Which could download zip or 7z files, extract them to PIK_ROOT, and add the version to the config file.

**Comment by deepj** [comment]
I think it would be great to have something like an option --source.

**Comment by rdp** [comment]
I had thought of doing something like this for jruby once.  A gem that installs jruby for you :)

**Comment by vertiginous** [comment]
The initial version of this will go into 0.2.0.  I'll look at a --source option in future release.  Also, in 0.2.0, the installable versions are hardcoded, in a future version, it will check for versions in a yaml file in a git repo.

**Comment by vertiginous** [comment]
Version 0.2.3 pulls package data directly from the rubyforge download page for IronRuby and Ruby mingw, and from jruby.org/downloads for JRuby. 

Have a look at 'pik help install' and 'pik list -r'  to see your options.
