### ISSUE TITLE
Error when running pik in Powershell

### ISSUE THREAD

**Issue by devert** [vertiginous/pik#140]
I installed the latest pik msi "pik-0.3.0.pre.msi" in Windows 7

Added C:\pik to PIK_HOME environmental variable and to the path.

I get the following error running pik in Powershell 1.0

"The splatting operator '@' cannot be used to reference variables in an expression. '@ECHO' can be used only as an argument
 to a command. To reference variables in an expression use '$ECHO'.
At C:\pik\pik.ps1:1 char:6
- @ECHO <<<<  OFF
  - CategoryInfo          : ParserError: (ECHO:String) [], ParseException
  - FullyQualifiedErrorId : SplattingNotPermitted"

**Comment by chiefy** [comment]
+1 (Windows 8)

**Comment by luislavena** [comment]
@devert and @chiefy I will recommend you use `uru` instead: 

https://bitbucket.org/jonforums/uru

While it doesn't install the versions of Ruby, it works much better than Pik.

Considering I haven't had time to work on pik over the last year or so, I think will be better option.

**Comment by ChrisTimperley** [comment]
+1 (Windows 8)

**Comment by luislavena** [comment]
@devert @chiefy @ChrisTimperley please see my previous comment from 5 months ago:

https://github.com/vertiginous/pik/issues/140#issuecomment-20770174

Use `uru` instead:

https://bitbucket.org/jonforums/uru/

Works with PowerShell.
