### ISSUE TITLE
How to pik install x64 version of Ruby 2.0?

### ISSUE THREAD

**Issue by jamlen** [vertiginous/pik#145]
Since there is now an x64 version of the Ruby 2.0 Installer, how can we install this version via pik?

And yes I know that you can manually install and then do a `pik add c:\ruby\ruby-2.0-p0-x64` but I wanted to script pik install.

I have tried various variations like `pik install ruby-2.0.0-p0-x64-mingw32`

As a side note, it might be worth implementing the RVM `rvm list known` to show which implementations you can install

**Comment by luislavena** [comment]
@jamlen current version of Pik might not be able to automatically install the 64bits version, however, you can manually download the package and then `pik add ...` it

The needed changes to detect other platforms might take more time.

There are several changes about building Pik itself that are blocking me to update the project :cry:

**Comment by tryveller** [comment]
@luislavena Do you know if pik has came up with a solution now to install x64 version of  ruby 2.0
(Since its been an year you last updated this thread )

**Comment by luislavena** [comment]
@DudeKumar no, I suggest you don't rely on Pik (or any other tool) to automatically install any version of Ruby for you.

Pik has become unmaintained for the previously mentioned issues and more importantly, lack of interest.

I suggest you switch to [Uru](https://bitbucket.org/jonforums/uru/) which is actively maintained. You will need to manually download and install Rubies, but that seems to be the less of the problems, as the important part is properly switching between versions :smile: 

Uru does that part perfectly and doesn't mess with other stuff.

I've replaced Pik with it long time ago and plan no go back.

**Comment by tryveller** [comment]
Thanks @luislavena .. I wasn't aware of Uru before. I shall try it and share my experience here.. For time being, i am still working with Pik ..
