### ISSUE TITLE
Which version of pik should we be using?

### ISSUE THREAD

**Issue by zhon** [vertiginous/pik#146]
I installed 0.3.0.pre quite some time ago. RubyGems installs pik 0.2.8.

Should I move back to 0.2.8 or forward to some other version?

**Comment by luislavena** [comment]
Please use `0.3.0.pre`

**Comment by zhon** [comment]
If you stumble here because of a gem install you will want to see issue [138](https://github.com/vertiginous/pik/issues/138)
