### ISSUE TITLE
Cannot install latest ruby versions like 2.1.0 also only 2 digit version is accepted by pik

### ISSUE THREAD

**Issue by iwx1** [vertiginous/pik#152]
below commands do not work with pik.
pik install ruby 1.8.6
pik install ruby 2.1
pik install ruby 2.1.0

following error is shown. 

There was an error.
 Error: private method `gsub' called for nil:NilClass

  in: pik/commands/install_command.rb:24:in `execute'
  in: pik_runner:33

Could you please fix the issues?
Pik is great thing and I want to continue using it. 
Please fix the bugs.

Thanks a lot!
~~ rahoolm

**Comment by luislavena** [comment]
Hello,

There is no Ruby 2.1 binary package released (officially) or that Pik is aware of.

Pik has been discontinued and no longer maintained.

I recommend manual installation of Ruby and manage of switching using uru instead:

https://bitbucket.org/jonforums/uru/
