### ISSUE TITLE
Feature request - Pik to inform if ruby version already installed

### ISSUE THREAD

**Issue by iwx1** [vertiginous/pik#153]
Pik is great for windows.

Pik should be able to recognize if a ruby version is already added or installed.

Currently when we give command below
pik install ruby 1.8 , it downloads the version even if it is already added.

Also, pik install ruby 1.9 installs 195 build. I think it is updated now.

rvm on Ubuntu gives a lot more.

Is it possible to choice different ruby build like I mean to say something like below

pik in ruby 1.8.7 -b 342

or is it possible to provide some url to pik in command?

like
pik install ruby -url http://dl.bintray.com/oneclick/rubyinstaller/ruby-2.0.0-p247-x64-mingw32.7z

it will be great to see such features.

Thanks a lot!!
~~ rahoolm

**Comment by luislavena** [comment]
Hello,

As mentioned in #152, pik is no longer maintained and it is recommended switch to something else, like uru:

https://bitbucket.org/jonforums/uru/
