### ISSUE TITLE
pik install ruby 2.1 : error

### ISSUE THREAD

**Issue by sevk** [vertiginous/pik#155]
C:\Documents and Settings\Administrator>pik install ruby 2.1

There was an error.
 Error: private method `gsub' called for nil:NilClass

  in: pik/commands/install_command.rb:24:in `execute'
  in: pik_runner:33

and pik install ruby is the old version 2.0.0-p195 

C:\Documents and Settings\Administrator>pik install ruby
*\* Downloading:  http://rubyforge.org/frs/download.php/76957/ruby-2.0.0-p195-i386-mingw32.7z
   to:  C:\Documents and Settings\Administrator.pik\downloads\ruby-2.0.0-p195-i
386-mingw32.7z

**Comment by iwx1** [comment]
See this..
https://github.com/vertiginous/pik/issues/152

**Comment by luislavena** [comment]
There is no Ruby 2.1 binary package released (officially) or that Pik is aware of.

Pik has been discontinued and no longer maintained.

I recommend manual installation of Ruby and manage of switching using uru instead:

https://bitbucket.org/jonforums/uru/
