### ISSUE TITLE
pik install ruby 2.0

### ISSUE THREAD

**Issue by Marko-L** [vertiginous/pik#156]
I would like an update if pik can install ruby 2.0 or greater. I read this post here https://github.com/vertiginous/pik/issues/152  that pik has been discontinued but that was in 2013. The reason is because  I am still getting the error:

There was an error.
 Error: private method `gsub' called for nil:NilClass

  in: pik/commands/install_command.rb:24:in `execute'
  in: pik_runner:33

If I installed ruby manually using rubyinstaller, I can manage 2 ruby installation however, there is a problem sharing gems between the 2 installations.

Please help.

**Comment by iwx1** [comment]
What is the exact issue you are facing? I don't know why pik development was stopped but I certainly like it when I work on Windows machine. Pik is great gem.

**Comment by Marko-L** [comment]
The issue is that I get an error above when I ran
 pik install ruby.
I have opted to install ruby using ruby installer and the manage ruby versions with pik. It looks good so far

**Comment by iwx1** [comment]
As per my understanding, after installing ruby using the ruby installer you just need to add it to pik using `pik add <dirpath to binary file ruby.exe>`. About my question, I was asking about the problem with sharing of gems between the 2 installations. Also, as the author of pik suggests using [uru](https://bitbucket.org/jonforums/uru), have you tried it? [uru](https://bitbucket.org/jonforums/uru) is also very simple and the thing you can do is download multiple versions of ruby from their site in .7z format , unzip them and add with [uru](https://bitbucket.org/jonforums/uru). It is quite simple.
Ruby version manager basically gives you freedom of using different ruby versions which have their own gems installed, so I was bit confused about sharing gems.

**Comment by luislavena** [comment]
You should not be sharing gems across different versions of ruby since each version differs in binary api, which affects C extensions compiled at installation time or already packaged with the gem for a specific version of ruby. 

Pik has been deprecated due the complexity in the code to maintain it. As suggested earlier you should use a simpler tool like uru, which performs the same functionality than Pik, except is maintained. 

Hope that helps.
