### ISSUE TITLE
Install pik in a separate path from Ruby

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#17]
I'm considering bundling a pik executable with Ocra, and having a pik_install command to install it to a different location that is in the path.  This would keep the code simpler, because I would only have to write it for MRI.  It would make supporting JRuby and IronRuby more straightforward.  It would also simplify the installation process.

RVM does something very similar, and it seems like the way to go.

Initial tests show that running an Ocra based pik would cause execution times on average of 2 seconds.  This is slower than running pik on 1.8.6 (around 0.5 seconds), but faster than running it with 1.9.1 or IronRuby (around 3 to 5 seconds).  

The way pik works, it needs to be started from a batch file.  The batch file would call the executable.  The executable would modify the bottom of the parent batch file.  When the executable finishes, the lines it added to the batch file gets executed.  This is how environment variables are set.  Simple, but effective.

**Comment by luislavena** [comment]
I like it, but the startup time is a killer.

What about exerb? permanent unpacking for every execution sounds irritating :P

**Comment by vertiginous** [comment]
It took some tweaking, but I got exerb working.  The speed issues... may not have been entirely Ocra's fault.  I've changed some of Pik's internals so it doesn't shell out to ruby for information as much.  This was the killer for IronRuby and jruby.  

IronRuby and jruby are still a little slow, because of printing the "Using jruby 1.3.1 (ruby 1.8.6p287)" line.  I may turn this off by default and make it optional.

http://gist.github.com/199263

**Comment by luislavena** [comment]
What if you cache the interpreter version information using a mtime of the interpreter executable as reference?

The interpreter changes, that invalidates the cache of the version information?

**Comment by vertiginous** [comment]
That's a possibility.  I have it this way to ensure the path actually gets changed as expected.  If it doesn't change, or changes to something else, It will print the real current version, or it will print an error if the executable name is different.  I think this is nice to have.  I just don't know if it needs to be there all the time.

**Comment by vertiginous** [comment]
Another exerb problem.  Win32ole throws a runtime exception.  I was using it for `pik default` to get the system path and gem_home env variables from the registry.  I'll have to fix win32ole or come up with an alternative method.

**Comment by luislavena** [comment]
Win32API calls? I thought DL has been wrapped as FFI on JRuby...

**Comment by vertiginous** [comment]
This is working in the new_features branch.  With pik being an exerb based executable, the code only needs to be compatible with Ruby 1.8.6.  I'm using Win32API isntead of Win32ole for 'pik default'.
