### ISSUE TITLE
Pik batchfile and executable clash

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#19]
My suggestion is around renaming the pik executable to something different than "pik".

This is because both bat and exe with same filename, exe take precedence of execution, and raises a corner case when user accessed Pik installation directory to check the installed Ruby versions.

Suggested name: pik_runner.exe

Thank you.

**Comment by vertiginous** [comment]
This is a very good idea.  Simple, but effective.

**Comment by vertiginous** [comment]
fixed in  b38f54794695d46b22f6cf28d42648056d208073
