### ISSUE TITLE
Error "can't dup NilClass" while switching

### ISSUE THREAD

**Issue by bhavinkamani** [vertiginous/pik#26]
Installed Pik without any issues

D:\Ruby>pik -v
pik 0.2.2

Added Ruby versions

D:\Ruby>pik list
187: ruby 1.8.7 (2008-05-31 patchlevel 0) [i386-mswin32]
191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]

Now when I try to switch I receive following error

D:\Ruby>pik sw 191

There was an error
 Error: can't dup NilClass

  in: pathname.rb:205:in `dup'
  in: pathname.rb:205:in`initialize'
  in: pathname.rb:1059:in `new'
  in: pathname.rb:1059:in`Pathname'
  in: pik/search_path.rb:42:in `replace_or_add'
  in: pik/commands/batch_file_editor.rb:30:in`switch_path_to'
  in: pik/commands/switch_command.rb:15:in `execute'
  in: pik:35

**Comment by vertiginous** [comment]
I believe I may have fixed this in 78348d27d578fc08eaddcd70142773cd547e68ce, but could you send me the output of:

```
pik ls -v
```

and

```
path
```

before and after you run pik sw 191?

Thanks,

Gordon

**Comment by bhavinkamani** [comment]
D:\Ruby>pik ls -v
187: ruby 1.8.7 (2008-05-31 patchlevel 0) [i386-mswin32]
     path: D:\Ruby\Ruby187\bin

191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]
     path: D:\Ruby\Ruby191\bin

D:\Ruby>set path
Path=C:\Program Files\Windows Resource Kits\Tools\;C:\WINDOWS\system32\WindowsPowerShell\v1.0;C:\Program Files\Sqlite;C:
\Program Files\PC Connectivity Solution\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\ALTool
s\ALZip;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\Program Files\ALTools\
ALZip;C:\Program Files\SlikSvn\bin\;D:\Ruby\Pik
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PSC1

D:\Ruby>set path=D:\Ruby\Pik

D:\Ruby>pik sw 191

There was an error
 Error: can't dup NilClass

  in: pathname.rb:205:in `dup'
  in: pathname.rb:205:in`initialize'
  in: pathname.rb:1059:in `new'
  in: pathname.rb:1059:in`Pathname'
  in: pik/search_path.rb:42:in `replace_or_add'
  in: pik/commands/batch_file_editor.rb:30:in`switch_path_to'
  in: pik/commands/switch_command.rb:15:in `execute'
  in: pik:35
D:\Ruby>pik ls -v
187: ruby 1.8.7 (2008-05-31 patchlevel 0) [i386-mswin32]
     path: D:\Ruby\Ruby187\bin

191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]
     path: D:\Ruby\Ruby191\bin

D:\Ruby>set path
Path=D:\Ruby\Pik
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PSC1

Changed the path to remove possibility of issue due to space...

**Comment by vertiginous** [comment]
I've rewritten BatchFileEditor#switch_path_to, and  fixed SearchPath#replace_or_add to handle nils better.  Let me know if this is fixed in the next release.

**Comment by vertiginous** [comment]
Assuming this is safe to close.
