### ISSUE TITLE
rake command

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#28]
```
pik rake spec

pik tags mingw rake spec
```

**Comment by luislavena** [comment]
You got my vote for this.

At this time this is what I do:

```
pik ruby -S rake ...
```

**Comment by vertiginous** [comment]
```
pik run rake ...
```

should work too, a _little_ fewer characters.  

This is an easy one to write, just subclassing the run command for rake, similar to gem and ruby.  But, I need to rewrite the path switching code in the Run class.  It seems there's a regression where the GEM_HOME bin dir doesn't get added to the path.  The path switching code is ugly, so I'm looking forward to cleaning it up a little.

**Comment by vertiginous** [comment]
added in a06a5f49d572a59818b6829f6548216c86d868a2
