### ISSUE TITLE
pik_runner.exe zlib1.dll was not found

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#29]
C:\dev\digitalarchive_trunk>pik cygwin

C:\dev\digitalarchive_trunk>pik mingw
[popup "pik_runner.exe zlib1.dll was not found"]

zip/zip.rb:5:in `require': Win32API Error #126 --- The specified module could not be found.
(ExerbRuntime::Error)

```
from zip/zip.rb:5
```

Unfortunately I seem to see this problem switching out of jruby, as well...

**Comment by vertiginous** [comment]
At some point I had copied zlib1.dll to C:\bin, which is always at the front of my path.  This means that pik will only work if zlib1.dll is in the path.  It will work for most (maybe all) MRI (mswin32|mingw32) versions, but is broken for JRuby, IronRuby, and apparently Cygwin.

Options:
-  Bundle zlib1.dll into the gem and add it to pik_install
  - I'm concerned about dll hell.
-  Bundle zlib1.dll into pik_runner.exe
  - This would require me to switch to exerb-mingw, and hand edit my .exy file.  Switching doesn't sound like a bad thing.  But, I like that my .exy is dynamically generated...
-  Remove the dependency on zlib1.dll
  - This will break install. (well, I guess it would just break the automatic download of 7za.exe, but...)

**Comment by luislavena** [comment]
You can still dynamically generate and play with your .exy file.

Since is a yaml file, I suggest you inject the dependency, or improve exerb-mingw to detect loaded DLLs, like Ocra is doing.

You need zlib1 since is a dependency of rubygems, which get included in your executable.

**Comment by vertiginous** [comment]
I like the injection idea.  Does it work with the original Exerb, or would I definitely have to switch to Exerb-mingw

Actually, I'm not requiring rubygems.  My only dependency is highline, and I downloaded it as a tar and installed it with setup.rb.  zlib1 is a dependency of the zip code I borrowed from rubyinstaller[1].  I could just remove the code that extracts the 7za.exe from it's zip file.  I'd have to raise an error and ask the user to install it themselves, though.  7za.exe handles extraction for everything else.

[1] http://github.com/vertiginous/pik/blob/master/lib/pik/contrib/zip/zip.rb#L5

**Comment by vertiginous** [comment]
Ok, I answered my own question.  It does appear to work with the original exerb.  Adding zlib1.dll only adds 60kb to the executable.

For now, I'm going in inject the dependency into the YAML file.  Hopefully soon I'll be able to switch to Exerb-mingw and try to work on DLL detection.

**Comment by luislavena** [comment]
Awesome!

**Comment by vertiginous** [comment]
fix to compile zlib1.dll into pik_runner.exe.  closed by 93f703a8d579e46ac19af6d70e4f350f78ef54bd
