### ISSUE TITLE
Feature: Tweak GEM_HOME and GEM_PATH when switching.

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#3]
Right now Ruby 1.8 and 1.9.1 cannot share gems, so setting GEM_HOME and GEM_PATH to one location is generating weird issues.

For example, see the 1.8.6 and 1.9.1 settings in the following gist:

http://gist.github.com/122851

Usage of GEM_HOME and GEM_PATH is to avoid that clash and to avoid gems installing inside Ruby itself, but instead a shared place.

**Comment by vertiginous** [comment]
I will fix this, but it may be a few days.

**Comment by luislavena** [comment]
No rush, I'll fork and send you a pull request :-D

**Comment by vertiginous** [comment]
have a look at the gem_home branch.  you'll have to delete and recreate your "%HOME%\.pik\config.yml" and recreate it.

you can add gem_home and gem_path with 'pik add_gem_home (pattern)'.

This assumes GEM_HOME and GEM_PATH are always the same.  Is that the case?

**Comment by vertiginous** [comment]
I'm pretty comfortable this is working well since 0.1.0
