### ISSUE TITLE
pik_install should check the validity of the arguments

### ISSUE THREAD

**Issue by vvs** [vertiginous/pik#38]
Hi,

As a pik newbie, I installed the pik gem and then invoked pik_install, with no arguments, and got:

D:\re>pik_install
Thank you for using pik.

D:/re/ruby-1.8.6-mingw/lib/ruby/gems/1.8/gems/pik-0.2.6/bin/pik_install:12:in `directory?': can't convert nil into String (TypeError)

Wasn't sure what's going on. Luckily Luis Lavena saved me here, and suggested that I missed the directory parameter. pik_install should probably check that no arguments are provided and print some friendly warning about that. :)

Thanks,
  --Vladimir

**Comment by vertiginous** [comment]
fixed in f85dc7f038f175955e270108dbb03e959930df70
