### ISSUE TITLE
pik_install should create directory if it is doesn't exist

### ISSUE THREAD

**Issue by vvs** [vertiginous/pik#39]
D:\re>pik_install D:\re\pik
Thank you for using pik.

D:\re\pik is not a directory.  pik was not installed.

Ideally, pik_install should try to create a specified directory if it doesn't exist.

**Comment by vertiginous** [comment]
I intentionally didn't do this.

Pik is meant to be installed to a directory that is in the path.  If it doesn't exist, then it's probably not in the path.  There is probably a better way to deal with this, though.  I'll think about it.

Thanks!

**Comment by vertiginous** [comment]
creates install dir if it doesn't exist, but warns about addign it to the system path. closed by cb73f266cf73dabc84e2f14aa596c39fea8090ed
