### ISSUE TITLE
pik sw works on 1.8.6, not 1.9

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#4]
only with 1.9

C:\dev\ruby\pik\pkg>pik sw 186
c:/ruby19/lib/ruby/gems/1.9.1/gems/vertiginous-pik-0.0.2/lib/pik/runner.rb:37:in `execute': wrong number of arguments (2 for 1) (ArgumentError)
        from c:/ruby19/lib/ruby/gems/1.9.1/gems/vertiginous-pik-0.0.2/lib/pik/runner.rb:6:in`execute'
        from c:/ruby19/lib/ruby/gems/1.9.1/gems/vertiginous-pik-0.0.2/bin/pik:20:in `<top (required)>'
        from c:/ruby19/bin/pik:19:in`load'
        from c:/ruby19/bin/pik:19:in `<main>'

C:\dev\ruby\pik\pkg>pik switch 186 # switch works, though
Select which Ruby you want:
1. 186: ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32]
2. 186: ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]
?  2
Switching to 186: ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]

**Comment by vertiginous** [comment]
is this still an issue?  You may just need to update pik on 1.9

**Comment by vertiginous** [comment]
No longer an issue on 0.1.0
