### ISSUE TITLE
Pik info fails when there is no default Ruby in use

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#40]
When there is no Ruby installation in the PATH, pik info fails:

<pre><code>
C:\Users\Luis>pik info -v
pik 0.2.6

There was an error.
 Error: undefined method `dirname' for nil:NilClass

  in: pik/commands/info_command.rb:15:in `info'
  in: pik/commands/info_command.rb:10:in `execute'
  in: pik_runner:35
</code></pre>

**Comment by vertiginous** [comment]
some fixes to info command -  closed by e69dc032c3f1bd5e5cddb7ac452cdc3c8b0ddb7f
