### ISSUE TITLE
pik info fails

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#41]
C:\dev\ruby\downloads\ruby_trunk_debug_flags>pik info

There was an error.
 Error: undefined method `[]' for nil:NilClass

  in: pik/commands/info_command.rb:17:in `info'
  in: pik/commands/info_command.rb:10:in`execute'
  in: pik_runner:35

C:\dev\ruby\downloads\ruby_trunk_debug_flags>ruby -v
ruby 1.9.2dev (2009-11-18 trunk 25830) [i386-mingw32]

**Comment by rdp** [comment]
seems to work now.

**Comment by deepj** [comment]
It doesn't work for me under Ruby 1.9.1p378

**Comment by vertiginous** [comment]
This -should- be fixed in the next release.  If not, let me know.
