### ISSUE TITLE
Incomplete message at version switcher prompt

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#42]
With the following list of versions:

http://gist.github.com/240688

When executed:

<pre><code>pik sw 191</code></pre>

And offered with the following list:

<pre><code>
Select which Ruby you want:
1. 191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]
2. 191: ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mswin32]
3. 191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]
?
</code></pre>

Hitting enter displays the following message:

<pre><code>Ambiguous choice.  Please choose one of [].</code></pre>

The [] should display a number or the list of available options, but somehow is not doing it.

Just a small cosmetic bug, so far, everything else has been joy!

Thank you!

**Comment by vertiginous** [comment]
This seems to be a highline issue.  I've created an issue for it.

http://github.com/JEG2/highline/issues/issue/5

**Comment by vertiginous** [comment]
Still waiting for the next version of highline to be released.

**Comment by vertiginous** [comment]
Fixed in 0.3.0.
