### ISSUE TITLE
pik add...fails?

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#44]
how to recreate:
navigate to a "new" ruby distro's bin directory
run pik add there

expected result:
it should add the ruby in the cwd.

actual result:

C:\installs\ruby19_mingw>cd bin

C:\installs\ruby19_mingw\bin>pik add
This version has already been added.

C:\installs\ruby19_mingw\bin>pik add .
*\* Adding:  191: ruby 1.9.1p376 (2009-12-07 revision 26041) [i386-mingw32]
 Located at:  C:\installs\ruby19_mingw\bin

I had expected it to work with the first add.
Is this expected?
-r

**Comment by luislavena** [comment]
Please read Pik help for add. You always need to specify the PATH of the Ruby installation you want to add.

**Comment by aslakhellesoy** [comment]
I can't add IronRuby 1.0:

<pre>
C:\ruby\IronRuby-1.0v4>pik add C:\ruby\IronRuby-1.0v4
Couldn't find a Ruby version at C:\ruby\IronRuby-1.0v4
</pre>

**Comment by luislavena** [comment]
Try specifying the `bin` directory:

<pre><code>pik add C:\Users\Luis\Tools\Ruby\ironruby-1.0v4\bin
This version has already been added.</code></pre>

**Comment by vertiginous** [comment]
@rdp, pik doesn't add based on the current directory.  If you run 'pik add'  with no args, it checks %PATH% for the first ruby version it finds (either ruby.exe, jruby.bat, jruby.exe, or ir.exe) and tries to add it.

In your case, try 'pik add %CD%'
