### ISSUE TITLE
pik rm fails?

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#46]
C:\installs\ruby_trunk_installed2>pik rm 192 1118

Quitting...

C:\installs\ruby_trunk_installed2>pik rm 192
Select which Ruby you want:
1. 192: ruby 1.9.2dev (2009-11-19 trunk 25849) [i386-mingw32]
2. 192: ruby 1.9.2dev (2009-11-18 trunk 25830) [i386-mingw32]
?  1
Are you sure you'd like to remove '192: ruby 1.9.2dev (2009-11-19 trunk 25849) [i386-mingw32]'?  |yes|
y
192: ruby 1.9.2dev (2009-11-19 trunk 25849) [i386-mingw32] removed.

[note also the extra line wrap on the remove command]

Not sure if these are expected.
-r

**Comment by vertiginous** [comment]
The pattern doesn't match.  Try:

```
 pik rm 192 11-18
```

or
     pik rm 192 25830

I'll look at the line wraps, though.

**Comment by vertiginous** [comment]
This can be closed.  Version 0.3.0 will use a different convention for choosing ruby versions.

http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b
