### ISSUE TITLE
pik_install fails re-"visita"-ed

### ISSUE THREAD

**Issue by jinjou** [vertiginous/pik#48]
Thank you for using pik.

Installing to C:/tools

cp ./../tools/pik.bat C:/tools
mkdir -p C:/tools/pik
cp ./../tools/pik/pik_runner.exe C:/tools/pik
C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1200:in `stat': No such file or directory - ./../tools/pik/pik_runner.exe (Errno::ENOENT)
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1200:in`lstat'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1178:in `stat'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1260:in`copy_file'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:463:in `copy_file'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:383:in`cp'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1395:in `fu_each_src_dest'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1409:in`fu_each_src_dest0'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:1393:in `fu_each_src_dest'
        from C:/Ruby/186-26/lib/ruby/1.8/fileutils.rb:382:in`cp'
        from pik_install:17

---

the above is the result of attempting to install "out of the box"

this is the failed command:
cp ./../tools/pik/pik_runner.exe C:/tools/pik

after checking "tools/pik/pik_runner" and finding it without the ".exe", adding it produced the result below

---

Thank you for using pik.

Installing to C:/tools

cp ./../tools/pik.bat C:/tools
mkdir -p C:/tools/pik
cp ./../tools/pik/pik_runner.exe C:/tools/pik

pik is installed

**Comment by vertiginous** [comment]
pik_runner (no extension) is a ruby file.  Adding the extension will allow it to be copied, but it won't run.  I'm not sure what happened to pik_runner.exe, but I know it's in the gem.

Try gem install pik again.
