### ISSUE TITLE
v0.2.6 pik_runner.exe is not compatible

### ISSUE THREAD

**Issue by jinjou** [vertiginous/pik#49]
v0.2.6

This version of C:\tools\pik\pik_runner.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

**Comment by luislavena** [comment]
What version of Windows are you using?

The executable that came with pik works on 32 and 64 environments.

This seems that the exe got corrupted.

Can you check a virus/trojan maybe? any minimal alteration to the executable will corrupt it.

**Comment by vertiginous** [comment]
Related to GH-48.  Please try to reinstall pik with gem install.
