### ISSUE TITLE
Pik commands fail under TCC/LE

### ISSUE THREAD

**Issue by charlesroper** [vertiginous/pik#50]
When using TCC/LE cmd.exe replacement, the pik command-line utility fails to run. Example: http://gist.github.com/300223

**Comment by charlesroper** [comment]
Changing the the 'runner' line in pik.bat to the following fixed it:

"%~dpn0\%~n0_runner.exe" "%~f0" %*

This also seems to work under vanilla cmd.exe

**Comment by vertiginous** [comment]
fixes pik.bat to run in tcc/le - closed by a0ebcffefdc1d277ed4ca30e7dcd22706b6ca102, thanks @charlesr
