### ISSUE TITLE
set default interpreter

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#51]
There is currently no way for pik to change the default ruby interpreter.  This might be nice to have, but the dangerous aspect of permanently changing a users environment is concerning.  I need to think this through some more.

**Comment by luislavena** [comment]
You mean something like rvm default?

That means that pik needs to be executed when a command prompt start or the user session.

For the user session (like autoexec.bat) is doable, but advised against it.

As for the execution with the prompt start, will require modification of the command prompt link...

IMHO: Pandora's box.

**Comment by chrismo** [comment]
or find a way to permanently change the PATH setting

**Comment by chrismo** [comment]
gem install patheditor ... maybe incorporate that?

**Comment by vertiginous** [comment]
there is code in pik to change the path permanently.  I've just been afraid to wire it up.  I'm trying to get a maintenance release out, and then I'll take some time to look at this.

**Comment by zdavatz** [comment]
Would be nice if one could do: pik 186 default and then it would set the default Ruby chosen. At the moment I always have to change to a different Ruby-Version with pik 186 because a new console starts up with 187 per default and I do not want that.

**Comment by luislavena** [comment]
That is because you have a Ruby installation that was added to your PATH.

To get this done require hooking into AutoRun functionality of the command processor, and Ruby has it issues when issuing child process that could interfere with `system` and friends.

**Comment by zdavatz** [comment]
Outstanding! Thanks! I deleted Ruby 1.8.7 from my Path. Now 1.8.6-p369-oniguruma is default and if I need 1.8.7 I can use pik or edit PATH. ;)

Thanks!
Zeno

**Comment by vertiginous** [comment]
The 0.3.0.pre version has this behavior.  Putting a pik call in autorun causes very weird behavior.  The best way to go is make a shortcut to cmd and put the call to pik default in there.  See: http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b
