### ISSUE TITLE
switching version creates 'lib' directory

### ISSUE THREAD

**Issue by semmons99** [vertiginous/pik#53]
Whenever I switch versions, a new directory is created (c:\lib\ruby\gems). I guessing this has something to do with GEM_PATH and GEM_HOME, neither of which are set in my configs.

**Comment by macler** [comment]
Switching doesn't work under Vista x64. When I try to switch then c:\lib is created.

**Comment by luislavena** [comment]
To confirm this, the issue is RubyGems 1.3.5, used by Pik internally. This has been solved with newer RubyGems.

**Comment by vertiginous** [comment]
I've switched from rubygems to crown.

Fixed in dfc8e31d438846493404
