### ISSUE TITLE
Shared devkit

### ISSUE THREAD

**Issue by deepj** [vertiginous/pik#54]
I'd like to specify a path to devkit for all ruby versions or only for selected versions :)

**Comment by vertiginous** [comment]
I do something like this.  

http://gist.github.com/123684

I'll think about how to add this to pik..

**Comment by vertiginous** [comment]
I'm working on an implementation where you can run:

```
 pik install devkit
```

and it will install it similar to a version of ruby, but won't add it to the config.  It will also write the necessary batch files to each mingw ruby version pik knows about.  

This is mostly done.  The only piece I have left to work on is writing batch files if you install a newer mingw ruby version after the devkit is installed.  I'm going to create a new command:

```
pik devkit update
```

This will add the missing batch files.

**Comment by vertiginous** [comment]
added in ab7dd0d2806cd5f0a4e1

**Comment by deepj** [comment]
Thx!
