### ISSUE TITLE
pik doesn't run in MingW32 (Git Bash shell)

### ISSUE THREAD

**Issue by mxriverlynn** [vertiginous/pik#55]
I run a git bash shell all day long to do the majority of my work, including the use of ruby. it's easier to work with ruby in this environment, for me, since i already have this shell open anyways. however, pik does not support this environment at all. the pik.bat file uses commands that are specific to the windows command prompt environment.

i would like to see a "pik" bash script that provides the same functionality to a MingW32 (Git Bash) shell, along side the pik.bat for the windows command prompt

**Comment by luislavena** [comment]
That will not be possible as pik depends on tricks done in batch files, bash is another beast and works differently.

You need something like rvm instead, which is based on bash. It might be possible trick it to avoid compilation and such, but I doubt.

PS: is MinGW, case matter :)

**Comment by mxriverlynn** [comment]
yeah, i was playing with this last night. i created a bash-specific version of the pik.bat file and i got that working fine. unfortunately the batch files that are produced by the pik runner aren't compatible, either. 

I'll see about using rvm (started looking at that last night, too). was hoping to have a single solution for both environments. oh well.

**Comment by vertiginous** [comment]
I think you would have better luck getting rvm to work under cygwin than pik.  I don't use git bash, but I would accept patches.

**Comment by vertiginous** [comment]
@derickbailey,  I'm not sure if you saw it, but I releases a new version last night that supports git bash.  Try it out and let me know if things work for you.

**Comment by mxriverlynn** [comment]
nice! got it set up and running now. i really love this tool. even before it had git bash support, it was using it daily. now i can REALLY love it with my git bash. :)
