### ISSUE TITLE
allow for case insensitivity...

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#58]
C:\Ruby19\bin>pik iron

There was an error.
 Error: The command 'iron' is unknown.

  in: pik_runner:33

C:\Ruby19\bin>pik ls -v
100: IronRuby 1.0.0.0 on .NET 4.0.30319.1
     path: c:\Program Files\IronRuby 1.0v4\bin

thanks!
-rp

**Comment by vertiginous** [comment]
Fixed in 7887ebc0f8ee314b77da
