### ISSUE TITLE
wrong file name in write_gcc

### ISSUE THREAD

**Issue by net1957** [vertiginous/pik#60]
in devkit_command.rb :

<pre>
    def write_sh(path)
      BatchFile.new(path + 'sh.bat') do |b|
</pre>

should be

<pre>
    def write_sh(path)
      BatchFile.new(path + 'gcc.bat') do |b|
</pre>

a typo ?

**Comment by vertiginous** [comment]
Very much a typo.  Thanks for pointing this out.

Fixed in c8ff61bad8fef1d3d4209b188ac3a9c93899b289

**Comment by vertiginous** [comment]
I have 3 open issues for devkit problems.  Consolidating to issue #83 .  Feel free to comment there.
