### ISSUE TITLE
pik update --freshen

### ISSUE THREAD

**Issue by jonforums** [vertiginous/pik#61]
When regularly building and installing MRI I have to perform a manual `pik rm` and `pik add` cycle in order for pik to display the correct summary info for `pik ls`

Consider adding `-f, --freshen` options to `pik update` that simply scans the installed rubies and updates pik's `config.yml` appropriately.

Thanks, Jon

**Comment by jonforums** [comment]
`-r, --refresh` are probably better option names as the `-f` reminds too much of `force`

**Comment by vertiginous** [comment]
Check out pik refresh in 0.3.0.  This will do what you want.
