### ISSUE TITLE
Installation succeeded but it won't run at all

### ISSUE THREAD

**Issue by chuckremes** [vertiginous/pik#64]
I installed pik 0.2.8 on a fresh Windows7 x64 vmware. I used the 'msiexec' installation method. It completed without error.

I opened a new command window and issued the "pik list" command. It wrote:

<pre>
There was an error.
 Error: can't dup NilClass

  in: pathname.rb:205:in 'dup'
  in: pathname.rb:205: in 'initialize'
  in: pik/commands/add_command.rb:17:in 'new'
  in: pik/commands/add_command.rb:17:in 'add'
  in: pik/commands/add_command.rb:13:in 'execute'
  in: pik_runner:27
</pre>

I am stumped on how to fix this.

**Comment by chuckremes** [comment]
It appears that pik requires a ruby to be installed somewhere already. I used rubyinstaller.org to install 1.9 and then reinstalled via the gem. It looks like it is working now.

**Comment by vertiginous** [comment]
I'm guessing you don't have any rubies installed since this is a fresh build.  If i remove all ruby bins from my path, I can reproduce.  This is a bug.  I'll try to come up with a workaround, but I'll fix it for the next release.

**Comment by vertiginous** [comment]
Yeah, this is a holdover from when pik could only be installed via gem install.  It assumes you have ruby installed, and tries to add it automatically.  

Create a fake config.yml file like this:
     --- 
    "fake: fools pik into running.": 

Then run 'pik install [ruby [1.8.6|1.9.1]|jruby|ironruby]' to install a version.  After something is installed, you can go in and clean up the fake line.  I'lll pull this code out for 0.2.9, since it doesn't make sense anymore.

Thanks,

**Comment by vertiginous** [comment]
oops, sorry, didn't see your initial reply =-)

**Comment by chuckremes** [comment]
I appreciate you jumping on this error report so soon. I found my own workaround but I'm glad the MSI installer will work for future versions.

Thank you for a great tool.

**Comment by cubanx** [comment]
Hello, I had this same error.  You didn't specify where to put the config.yml :)  

I tried in the root of my pik install, but that didn't work.

After a little bit of hunting in the batch file, I found %USERNAME%.pik.  I put the config.yml file there, and it worked a treat :)

Thanks!
