### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by eloyesp** [vertiginous/pik#67]
Is it possible to use pik in portable mode?
This is: I want to put it in my pen drive to have ruby without touch the host computer...
In my computer I would like to copy the folder and start coding.

**Comment by vertiginous** [comment]
Version 0.3.0 will support this.  I'm tracking this issue in issue #80

**Comment by vertiginous** [comment]
Sorry, hit comment too soon.  If you want to keep up with this, please comment in issue #80.  Thanks
