### ISSUE TITLE
Any command simply fails with "Permission denied" while creating the .pik directory.

### ISSUE THREAD

**Issue by JoergWMittag** [vertiginous/pik#68]
Any command I run, even a simple `pik help`, fails with the exact same error message:

```
C:\Users\JRGWMI~1>pik help
creating C:\Users\Jörg W Mittag\.pik

There was an error.
 Error: Permission denied - C:\Users\Jörg W Mittag

  in: fileutils.rb:243:in `mkdir'
  in: fileutils.rb:243:in `fu_mkdir'
  in: fileutils.rb:217:in `mkpath'
  in: fileutils.rb:215:in `reverse_each'
  in: fileutils.rb:215:in `mkpath'
  in: fileutils.rb:201:in `each'
  in: fileutils.rb:201:in `mkpath'
  in: pathname.rb:1028:in `mkpath'
  in: pik/commands/command.rb:154:in `create'
  in: pik/commands/command.rb:83:in `initialize'
  in: pik/commands/config_file_editor.rb:6:in `initialize'
  in: pik_runner:26:in `new'
  in: pik_runner:26
```

I checked and re-checked and the permissions are _definitely_ fine.

This occurs on Windows 7 Professional 32 Bit.

This error originally occured when I installed pik as a Gem. I did already have 9 Ruby installations installed manually at that point, so I thought it might have been a problem with my setup. I uninstalled all existing installations and purged the system from every trace of them, then installed pik via the MSI package, but got the same result.

I simply don't understand how there could be a permissions problem. My entire user directory including all subdirectories and all files is owned by me, readable by me and writable by me. And the only _other_ user account on the system is an administrative account which has full access anyway, so even _if_ for some strange reason pik ran under the wrong user account without popping up a UAC dialog, it _still_ should have full permissions.

EDIT: I completely forgot: it _did_ actually work two months ago. I am currently writing a manual for the usage of Ruby in Windows 7, and I just went back through my commit log and found a commit from May, 17 2010 which adds the chapter about pik. And I know 100% that I did actually install and use pik at that time and in fact copy&pasted example commands from the Windows Command Prompt into the manual.

Then I uninstalled both pik and all my Rubies, and installed them again without pik. Today, I tried to install pik again, following the steps I wrote in the manual (i.e. 100% exactly reproducing what I did three months ago) and it didn't work.

So, either something very subtle changed in my setup within the last three months (note this was the same machine, the same username, the same home directory, the same environment variables), or something changed in the way pik calculates the path to the home directory.

**Comment by vertiginous** [comment]
I don't think this is a permissions problem.  I think it's an issue of my code not handling the name of your home dir properly.  I think it's trying to create a new folder at C:\users, instead of trying to create .pik in your home dir.

**Comment by vertiginous** [comment]
Can I get the ouput of 'set user' and 'set home' on your machine, please?

**Comment by JoergWMittag** [comment]
```
C:\Users\JRGWMI~1>set user
USERDOMAIN=Schlepptop
USERNAME=Jörg W Mittag
USERPROFILE=C:\Users\Jörg W Mittag

C:\Users\JRGWMI~1>set home
HOME=C:\Users\JrgWMi~1
HOMEDRIVE=C:
HOMEPATH=\Users\Jörg W Mittag
```

As you can see, I already have manually set `%HOME%` to the 8.3 ASCII shortname of my home directory, because otherwise MSysGit freaks out completely. Would that be an acceptable workaround? Simply require users which have whitespace and/or non-ASCII characters in their username to set `%HOME%` to a pure ASCII pathname? It would be acceptable for me, at least.

**Comment by vertiginous** [comment]
Actually, that was the way pik worked until 0.2.8.  I took it out to simplify things.  I'll set it back to checking for %HOME% first, then %USERPROFILE% second.

**Comment by JoergWMittag** [comment]
I forgot: it _did_ actually work three months ago, on the same machine with the same username, home directory, and environment variables. See the edit above for details.

EDIT:

> Actually, that was the way pik worked until 0.2.8. I took it out to simplify things. I'll set it back to checking for %HOME% first, then %USERPROFILE% second.

And that explains it, of course.

**Comment by JoergWMittag** [comment]
For anyone watching: the relevant commits are a9af53561f50c5c59d44f8d7c1a40e2bf99de0a5#L5L57 and 450e07d5c8a7e4d960d20acf2bf8ba5980e45654#L0R30 I believe.

Thank you very much for jumping on this so quickly! And I apologize for not realizing right away that it was an encoding issue. I _really_ should have known, considering that I have struggled with getting computers to understand my name for 20 years now.

**Comment by vertiginous** [comment]
Thanks for the report.  The next release will probably have:

```
module Pik
  def self.home
    @home ||= Pathname(ENV['PIK_HOME'] || ENV['HOME'] || ENV['USERPROFILE']) + '.pik'
  end
end
```

This way, if the user wants to have pik files in a different location, (like a portable drive - issue #67), they can set `%PIK_HOME%.`

**Comment by vertiginous** [comment]
This is fixed in 0.3.0, which should be released by the end of the week.

http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b

**Comment by JoergWMittag** [comment]
Thanks for this! I'm probably gonna be able to test out the [0.3.0.pre MSI package](https://GitHub.Com/downloads/vertiginous/pik/pik-0.3.0.pre.msi) sometime tomorrow.

**Comment by JoergWMittag** [comment]
It works now. Thanks for fixing it!
