### ISSUE TITLE
doesn't work with jruby

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#7]
Situation:
C:\dev\ruby>pik add c:\installs\jruby-bin-1.3.0\jruby-1.3.0\bin
This is not a valid path to ruby.exe

Thanks!
=r

**Comment by luislavena** [comment]
JRuby is tricky since the entry point is a batch file, which can affect and terminate the execution of pik own batch file.

Just my 2 cents.

**Comment by rdp** [comment]
appears you can use the "call" command 
or perhaps command /c "batch file" which is what I've used in the past.
-r

**Comment by vertiginous** [comment]
I was getting close to a working solution, but jruby doesn't support win32ole, and pik needs to have it right now.

**Comment by vertiginous** [comment]
This is working in the new_features branch.  With pik being an exerb based executable, the code only needs to be compatible with Ruby 1.8.6.  

Support for any Ruby implementation is easy to add.  The only prerequisite is that it must have a --version parameter.
