### ISSUE TITLE
pik install devkit creates incorrectly named batch files

### ISSUE THREAD

**Issue by charlesroper** [vertiginous/pik#70]
This is on Win7 x64. Pik creates the following batch files in the Ruby bin folders:

gcc.bat.bat
make.bat.bat
sh.bat.bat

Here's a screenshot: http://i.imgur.com/6tGiA.png

**Comment by vertiginous** [comment]
This was fixed in c8db0cc20072ea096d92 and was planned to be available in the next release.  The batch file stubs are in a state of flux right now[1], so I may change this behavior entirely.

[1] http://groups.google.com/group/rubyinstaller/browse_thread/thread/d260051014f32e1

**Comment by vertiginous** [comment]
I have 3 open issues for devkit problems.  Consolidating to issue #83 .  Feel free to comment there.
