### ISSUE TITLE
'pik install jruby' fails with 'Error: private method 'gsub' called for nil:NilClass' on Win7x64

### ISSUE THREAD

**Issue by chuckremes** [vertiginous/pik#71]
Run:

pik install jruby

Error I get is:

<pre>
There was an error.
 Error: private method 'gsub' called for nil:NilClass

  in: pik/commands/command.rb:124:in 'get_version'
  in: pik/commands/add_command.rb:23:in 'add'
  in: pik/commands/add_command.rb:13:in 'execute'
  in: pik/implementations.rb:91:in 'after_install'
  in: pik/commands/install_command.rb:27:in 'execute'
  in: pik_runner:33
</pre>

This is on Win7 x64 with latest patches. I also am running pik 0.2.8. I ran 'pik up' to make sure I wasn't missing any fixes, but it failed exactly the same way.

**Comment by luislavena** [comment]
It works for me.

<pre><code>C:\Users\Luis>pik install jruby
** Downloading:  http://jruby.org.s3.amazonaws.com/downloads/1.5.1/jruby-bin-1.5.1.zip
   to:  C:\Users\Luis\.pik\downloads\jruby-bin-1.5.1.zip

jruby-bin-1.5.1.zip:   3% |                    | 530.2KB/ 17.2MB ETA:  00:04:44</code></pre>


<pre><code>C:\Users\Luis>pik --version
pik 0.2.8</code></pre>


It might be a network connection problem. Are you behind a proxy or firewall?

**Comment by chuckremes** [comment]
This is not behind a proxy or firewall. The Windows firewall has also been disabled.

Clearly some operation along the line is returning nil and the downstream code doesn't know how to detect or recover from it. I'll try to troubleshoot it some more. In the meantime, I'll install jruby manually.

**Comment by DanRathbun** [comment]
I got the same problem when I tried to install 1.8.7
pik install ruby 1.8.7

I installed pik using the msi database, and not a gem.
Perhaps I'm missing something, that the gem has.

**Comment by marcelotto** [comment]
I get the same when I try to install 1.8.6. Installation of 1.8.7 and 1.9.1 works perfectly fine.

**Comment by vertiginous** [comment]
This was a flaw in the way pik 0.2.8 worked, but was only visible if you didn't already have a ruby version installed on your machine.  This should be fixed in version 0.3.0

http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b

Please try out the new MSI and let me know.

**Comment by miau** [comment]
The new MSI installer works fine without any ruby version installed. Thanks!

**Comment by duinness** [comment]
I saw this issue occur on 0.2.8. 
The reason was because JAVA_HOME was not pointing to the JDK

**Comment by duinness** [comment]
This sounds really similar to this
http://stackoverflow.com/questions/11425163/pik-error-private-method-gsub-called-for-nilnilclass

JAVA_HOME was the culprit

**Comment by hoffm386** [comment]
I'm getting this error message whenever I try to install various versions of Ruby (1.9.3, 2.0.0, 2.1.1, etc.) with pik.  I tried installing JRuby just to see if "pik install" was broken completely, but JRuby installed just fine, so I don't think this is related to JAVA_HOME.  I currently have 1.9.3 installed with RailsInstaller (which pik displays with the "list" command), so the "if you didn't already have a ruby version installed on your machine" situation isn't what's happening either.

**Comment by Tuman829** [comment]
I have the exact same issue as @hoffm386

**Comment by luislavena** [comment]
@Tuman829 @hoffm386 @miau @duinness 

Pik has been considered deprecated, use something like `uru` instead:

https://bitbucket.org/jonforums/uru/

You need to manually install JRuby or any other Ruby interpreter.
