### ISSUE TITLE
method 'help' undefined for Pik::Devkit

### ISSUE THREAD

**Issue by jarmo** [vertiginous/pik#74]
S:>pik devkit

There was an error.
 Error: undefined local variable or method `help' for #Pik::Devkit:0x316a478

  in: pik/commands/devkit_command.rb:19:in `execute'
  in: pik_runner:33

S:>pik --version
pik 0.2.8

**Comment by phiggins** [comment]
This is a dup of this one: http://github.com/vertiginous/pik/issues#issue/66

**Comment by jarmo** [comment]
seems so, sorry
