### ISSUE TITLE
Add new DevKit 4.5.0 option.

### ISSUE THREAD

**Issue by semmons99** [vertiginous/pik#76]
Add the option to install the new DevKit 4.5.0

**Comment by jarmo** [comment]
+1

and it's 4.5.1 now - it is a must have since there are already gems which are failing with older devkit... also when upgrading devkit from the older version then some manual steps have to be taken - "How do I uninstall the legacy DevKit?" at https://github.com/oneclick/rubyinstaller/wiki/FAQ

**Comment by vertiginous** [comment]
I'm looking at this.  The problem is that the 4.5.1 version is only available on github downloads, which is SSL encrypted.  I don't bundle openssl with pik and don't want to.  Hopefully we'll come up with a resolution soon.

**Comment by jarmo** [comment]
What are you using for downloading? I'm not sure but does "net/https" depend from openssl?

If it does, then one other possible way would be to bundle wget/curl and then use some switch similar to --verify-none to ignore certificate validation.

**Comment by vertiginous** [comment]
I'm hoping to get the rubyinstaller folks to host the package on rubyforge, but if that doesn't work out, I'll explore the wget/curl option.

**Comment by vertiginous** [comment]
I have 3 open issues for devkit problems.  Consolidating to issue #83 .  Feel free to comment there.
