### ISSUE TITLE
Infinite recursion in Pik::Install.extract

### ISSUE THREAD

**Issue by voxik** [vertiginous/pik#77]
I have no 7zip on path of my computer. Also I am running pik from folder which is not in search path. So first time I am trying to install some ruby, Pik downloads and extracts 7zip. However, later it can't find it while recursive calling the extract method.

I believe that the correct approach should be to extract 7zip under the .pik directory and explicitly look for 7zip on that place.

Nevertheless, the problem is also probably the Which class, which does not look for the 7zip in the current directory. I cant confirm it since I uninstalled Ruby and now I am struggling with installation of new version a bit :)

**Comment by vertiginous** [comment]
The installation instructions are pretty clear about installing pik to a location in your search path.  If you don't want to permanently add it, just run

```
set PATH=C:\pik;%PATH%
```

or whatever path you need.

**Comment by voxik** [comment]
Sorry, but that is not true. Path is mentioned in case you are installing pik as a gem, but I started with plain computer, without any Ruby. Then I installed Pik using windows installer and I would expect it will simply work, even without modifying path. But that is not true and the path is not mentioned in "Installer" section.

**Comment by voxik** [comment]
Ok sorry, you are right, you mention that you can modify path yourself but there is not obvious the reason why to do that.

If I decide that I don't want clutter my path with pik, then it is sad that it doesn't work fully qualified.

**Comment by vertiginous** [comment]
From the readme, under the "Install pik using the installer" section;

```
If you install to a directory that’s not in your path, you’ll need to add it to the path yourself
```

The installer is far from perfect, I admit.  I'm working on a better solution.

**Comment by vertiginous** [comment]
Why would you want a command line tool that's not in your path? I'm not even saying you should add a separate folder for pik, just add C:\bin to the path, and put anything you want in there.  That's just my opinion.  It's your  computer, and your choice.

Maybe it's not a good idea to assume that pik is in the path, it just seems awfully limiting.  I'll see what I can do to address this.

Another solution could be to abort and prompt the user to install 7zip.  I opted for what I thought would be a convenience for the user.

**Comment by voxik** [comment]
It depends how extensively you plan to use Pik. At that time I needed to install Ruby and I wanted to be prepared for future versions. So modifying path was bit too much. Even now I am using Pik just once in a while.

Moreover the MS dialog for path modification is the worst part of Widnows UI, but that is different story ;)
