### ISSUE TITLE
portable pik installation

### ISSUE THREAD

**Issue by jcangas** [vertiginous/pik#80]
I want setup shared/portable installation of pik and some rubies. I created the structure 

```
    /pik
    +--/rubies
    +--/bin
    +--/temp
```

and all works ok. My problem is it seems config.yml is forced to be at userhome folder. I tried to put in bin dir, but pik ignore it and recreates a new config.yml.

There are a way to put all pik stuff into a root dir, some like w:/pik? This way I can carry all my rubies in my pen drive or easy share it in a network or the many VirtualBox running in my laptop :)

Thanks a lot for this so great tool!

**Comment by luislavena** [comment]
Hello, At this time is not possible what you're suggesting, but feel free to fork the project and contribute a lookup path for the configuration file.

After all, the code is written in Ruby ;-)

**Comment by prabirshrestha** [comment]
this is also one of the feature i have been waiting for.

another note is most of the linux tools running under windows, saves the configuration in $HOME, if it is present else in $USERPROFILE.
i prefer to have $HOME and $USERPROFILE set in different directory. would be nice if pik too looks up in $HOME directory first then the $USERPROFILE,
this is the default behavior for git,gitk,kdiff,vim,hg,ssh and so on. this allows me to save my configurations of HOME directory in source control easily.

**Comment by vertiginous** [comment]
Ok, version 0.3.0 will use %PIK_HOME% first, then %HOME%.  Let me know if this meets your needs.

http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b

**Comment by jcangas** [comment]
Great news!! Thanks to this change, now I have pik portable installation: Only thing I has done is add a line at top of pik.bat. The line is

```
set PIK_HOME=%~dp0%
```

and voilà!.

I miss the pik config command. I need it to change the pik downlad folder.  Is a bug or a pending feature to 0.3 release?

Anyway thanks a lot: the new pik looks a lot better!!

**Comment by vertiginous** [comment]
I think manually editing the config file might be the best option ( though it wouldn't work right now).  I'll think about this some more.

**Comment by jcangas** [comment]
Already done and it don't work. This is my entry in config.yml

```
:download_dir: !ruby/object:Pathname 
  path: w:/pik/temp
```

But pik continue using bin/downloads. I think manually editing the config is fine, but the avaiable keys need be documented. Maybe pik can generate a commented config.yml that show all the options avaiable.

**Comment by vertiginous** [comment]
Yes, I yanked out the code that checks for the config options.  I'll have to put them back in.  Would you mind starting a new issue for this?

**Comment by jcangas** [comment]
reported as https://github.com/vertiginous/pik/issues/#issue/86
