### ISSUE TITLE
prioritize ruby version over patchlevel on switch

### ISSUE THREAD

**Issue by jonforums** [vertiginous/pik#82]
As a feature tweak I'd like to request that when switching between different install rubies that the ruby version is prioritized over the patchlevel when the two match.  For example:

```
C:\Users\Jon\Documents\RubyDev>pik ls
  160: jruby 1.6.0.RC1 (ruby 1.8.7 patchlevel 330) (2011-01-10 769f847) (Java...
  187: ruby 1.8.7 (2010-12-23 patchlevel 330) [i386-mingw32]
* 192: ruby 1.9.2p160 (2011-01-16 revision 30579) [i386-mingw32]
  193: ruby 1.9.3dev (2011-01-19 trunk 30603) [i386-mingw32]
```

...so that manually confirmations like the following can be minimized

```
C:\Users\Jon\Documents\RubyDev>pik sw 160
Select which Ruby you want:
1. 160: jruby 1.6.0.RC1 (ruby 1.8.7 patchlevel 330) (2011-01-10 769f847) (Java HotSpot(TM) Client VM 1.6.0_23) [Windows 7-x86-java]
2. 192: ruby 1.9.2p160 (2011-01-16 revision 30579) [i386-mingw32]
?  2
```

**Comment by vertiginous** [comment]
The 0.3.0 version of use has a more explicit system for finding ruby versions.  Let me know if that meets your needs.

**Comment by jonforums** [comment]
The `pik alias` feature looks perfect and this request can be closed.

**Comment by vertiginous** [comment]
Thanks, Jon
