### ISSUE TITLE
pik package devkit install

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#83]
I hope to add the new devkit as a package in pik 0.3.0.  I can use the 
current sfx installer, 7za.exe can handle extracting the files fine. 
My problem is with github downloads.  I don't want to have to bundle 
the openssl dll's with pik, as I can see that causing conflicts with 
ruby's versions of the dll's in the future.  So, I have a request... 
Would it be possible to put the devkit package on rubyforge, or 
somewhere else that is not using ssl?  I think I have the ability to 
add it on rubyforge, so with permission, I can take care of putting it 
up there. 
Once that hurdle is overcome, I may need help with automating the 
devkit installation process.  I'm not sure how well dk.rb handles 
being run over a previous install. 

http://groups.google.com/group/rubyinstaller/browse_thread/thread/25b770c4a5fb74d5

**Comment by vertiginous** [comment]
Another possibility is to use wget or curl.  See issue #76

**Comment by jarmo** [comment]
Just took a glimpse on the code itself and saw in https://github.com/vertiginous/pik/blob/master/lib/pik/contrib/uri_ext.rb a `require "net/https"` commented out for some reason.

In #connect method there is:
    http.use_ssl = true if self.instance_of? URI::HTTPS

Why not uncomment the require statement and add an additional line like this:
    if self.instance_of? URI::HTTPS
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    end

I haven't tested it, but why shouldn't it work?

Also in packages.yml there is a pik 0.3.0, which is also using https (https://pik.cloudfront.com/pik-0.3.0.zip) - how does it work? Or does it?

**Comment by vertiginous** [comment]
The only way net/https will work is if I bundle libeay32-0.9.8-msvcrt.dll and ssleay32-0.9.8-msvcrt.dll with pik.  I don't want to do that, as it could cause dll problems with other versions of ruby.  That's why I commented out the https code.

The pik 0.3.0 url is a placeholder.  It doesn't work.  

The ruby installer folks are going to put the package up on a plain http url for me.

**Comment by vertiginous** [comment]
Implemented.  Closing
