### ISSUE TITLE
add pik automatically to PATH with WiX

### ISSUE THREAD

**Issue by jarmo** [vertiginous/pik#84]
I noticed in the readme:
    If you install to a directory that’s not in your path, you’ll need to add it to the path yourself. Microsoft has good instructions on that. After that, you should be ready to run pik

This could be done relatively easily with WiX itself:
    http://wix.sourceforge.net/manual-wix3/wix_xsd_environment.htm

**Comment by vertiginous** [comment]
This is actually available in the new installer.  I need to update the readme.

Thanks!

**Comment by vertiginous** [comment]
Readme updated, closing.
