### ISSUE TITLE
Support ruby aliasing

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#85]
Hello,

Since version 0.3.0 removes the support for quick lookup of versions (like `pik 187`) I was wondering if version aliasing could be added?

Something like RVM does:

http://rvm.beginrescueend.com/rubies/alias/

`pik alias 187 ruby-1.8.7-p330`

Thank you!

**Comment by vertiginous** [comment]
This should be simple enough.  It could work similar to pik default.

**Comment by vertiginous** [comment]
Added in 5dcf48c0b2ac87fe2043faf6478e54eb5c736c15

```
C:\>pik alias create 192 1.9.2-p136

C:\>pik alias list
192 => ruby-1.9.2-p136


C:\>pik alias create 187 1.8.7-p302

C:\>pik alias list
192 => ruby-1.9.2-p136
187 => ruby-1.8.7-p302


C:\>pik 192

C:\>ruby -v
ruby 1.9.2p136 (2010-12-25) [i386-mingw32]

C:\>pik 187

C:\>ruby -v
ruby 1.8.7 (2010-08-16 patchlevel 302) [i386-mingw32]

C:\>pik alias delete 187

C:\>pik alias list
192 => ruby-1.9.2-p136
```

**Comment by jonforums** [comment]
When aliases have been created, what does rvm show for `rvm list`?  It might be nice for pik to have something similar to:

<pre>
C:\Users\Jon\Documents>pik alias list
192 => ruby-1.9.2-p160
187 => ruby-1.8.7-p330

C:\Users\Jon\Documents>pik ls
   ruby-1.8.7-p330  [187]
=> ruby-1.9.2-p160  [192]
   ruby-1.9.3-dev
   jruby-1.6.0

C:\Users\Jon\Documents>pik ls -v
   ruby-1.8.7-p330  [187]
        version: ruby 1.8.7 (2010-12-23 patchlevel 330) [i386-mingw32]
        alias: 187
        path: C:\ruby187\bin

=> ruby-1.9.2-p160  [192]
        version: ruby 1.9.2p160 (2011-01-16 revision 30579) [i386-mingw32]
        alias: 192
        path: C:\ruby192\bin

  ...
</pre>

**Comment by vertiginous** [comment]
rvm list output doesn't change when aliases are defined on RVM.  The only way I see to access alias information is with rvm alias list.

We already have more different list commands than RVM, I don't want to deviate any more.

**Comment by jonforums** [comment]
got it re: rvm behavior.  i still like the idea but not enough to advocate more for it and slow down 0.3.0 final.

**Comment by vertiginous** [comment]
Just realized the refresh command deletes all aliases.  Need to fix that.

**Comment by vertiginous** [comment]
Fixed refresh command, made default an alias.  I'm happy with the alias implementation.  Closing.
