### ISSUE TITLE
pik ignores downlad path in config.yml

### ISSUE THREAD

**Issue by jcangas** [vertiginous/pik#86]
This is my entry in config.yml

```
:download_dir: !ruby/object:Pathname 
  path: w:/pik/temp
```

But pik continue using bin/downloads

**Comment by vertiginous** [comment]
This has been implemented.  I plan to push out a new package this weekend.  Since this requres manually editing the config file, you can use:

```
:download_dir: w:/pik/temp
```

Pik will convert to pathnames.  I'd like to move these sorts of options into a separate file, though.  I'll add another issue for that.
