### ISSUE TITLE
7z issues

### ISSUE THREAD

**Issue by voxik** [vertiginous/pik#87]
I am trying pik 0.3.0.pre

```
C:\>pik -V
pik 0.3.0.pre
by Gordon Thiesfeld (gthiesfeld@gmail.com)
```

and have some troubles with 7z:

1) Altough there is known that installation fails, it continues anyway:
    C:>pik in 1.9.2
    INFO: Installing ruby-1.9.2-p136

```
ERROR: You need the 7zip utility to extract this file.
Run 'pik package 7zip install'

INFO: Downloading:  http://rubyforge.org/frs/download.php/73723/ruby-1.9.2-p136-i386-mingw32.7z
      to:  C:\Users\vita\.pik\downloads\ruby-1.9.2-p136-i386-mingw32.7z

ruby-1.9.2-p136-i386-min...7z: 100% |oooooooooo|   5.8MB/  5.8MB Time: 00:00:05
INFO: Extracting:  C:\Users\vita\.pik\downloads\ruby-1.9.2-p136-i386-mingw32.7z
      to:  C:\Users\vita\.pik\rubies\ruby-1.9.2-p136

x není názvem vnitřního ani vnějšího příkazu,
spustitelného programu nebo dávkového souboru.
      Extraction complete.
Couldn't find a Ruby version at C:\Users\vita\.pik\rubies\ruby-1.9.2-p136\bin
```

2) Installing 7zip without 7zip might be problem, however it is probably just false alarm? But anyway, admin rights are required for some locations, which is not very nice.

```
C:\>pik package 7zip install
ERROR: You need the 7zip utility to extract this file.
Run 'pik package 7zip install'

INFO: Downloading:  http://downloads.sourceforge.net/sevenzip/7za920.zip
      to:  C:\Users\vita\.pik\downloads\7za920.zip

7za920.zip: 100% |ooooooooooooooooooooooooooooo| 375.8KB/375.8KB Time: 00:00:06

There was an error.
 Error: Permission denied - C:\Program Files (x86)\pik/7za.exe

  in: zip/zip.rb:834:in `initialize'
  in: zip/zip.rb:834:in `open'
  in: zip/zip.rb:834:in `write_file'
  in: zip/zip.rb:465:in `extract'
  in: zip/zip.rb:1469:in `extract'
  in: pik/contrib/unzip.rb:9:in `fake_unzip'
  in: zip/zip.rb:1122:in `each'
  in: zip/zip.rb:1122:in `each'
  in: zip/zip.rb:1265:in `each'
  in: zip/zip.rb:1402:in `foreach'
  in: zip/zip.rb:1381:in `open'
  in: zip/zip.rb:1400:in `foreach'
  in: pik/contrib/unzip.rb:7:in `fake_unzip'
  in: zip/zip.rb:1381:in `open'
  in: pik/contrib/unzip.rb:6:in `fake_unzip'
  in: pik/commands/package_command.rb:49:in `sevenzip'
  in: pik/commands/package_command.rb:14:in `execute'
  in: pik_runner:27
```

**Comment by vertiginous** [comment]
Hmm, I'll have to fix my logic for checking for 7zip.  The error about installing 7zip without 7zip is definitely a false alarm.

As far as installing to locations like %PROGRAMFILES%, that's just going to be a problem.  If you definitely want to install it there, you could run the command as administrator.  Otherwise, you could use the path parameter to install it elsewhere.  Maybe I could put a tools folder inside ~/.pik, and have pik check there for 7zip?

**Comment by voxik** [comment]
yes, the ~/.pik folder is the right place IMO.

**Comment by vertiginous** [comment]
I'm sorry, I most certainly didn't mean to close this issue.  I don't think there is a way to open it again either.  

I believe I have fixed the 7zip checking logic in 7334f88  and I believe you created a separate issue for the %PROGRAMFILES% problems, so I don't guess we need to reopen it.

Thanks,

**Comment by voxik** [comment]
The checking seems to be fine with the latest version.

How about the admin rights for the 7z installation? Should I create separate ticket for this? Because it IMO different topic then %PROGRAMFILES% ...

**Comment by vertiginous** [comment]
Yes, please.  But, I'm still not sure how I feel about this topic.  Applications writing to %PROGRAMFILES% is not generally a good idea.  And I'm not keen on checking yet another place outside of the path for executables.  I'll think on it.
