### ISSUE TITLE
feature: pik run without the quotes

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#9]
would it be possible to make quotes optional for pik run arguments?
i.e.
pik run "something"
or
pik run it will run all of these parameters?
That might be nice.
Anyway just throwing it out there.
-r

**Comment by vertiginous** [comment]
With the way pik currently does option parsing, this is impossible.  Pik would swallow any options you're trying to pass to the other command.

pik run rake -T

would run rake default against all versions of ruby.  I'm going to rewrite the option parsing some time soon, and when I do that, I'll see if this is feasible.

**Comment by vertiginous** [comment]
Sorry, I'm concerned about unexpected side effects..
