### ISSUE TITLE
[0.3.0.pre] pik refresh should update .pik\pik_run.bat

### ISSUE THREAD

**Issue by jonforums** [vertiginous/pik#95]
Currently it appears `.pik\pik_run.bat` is created the first time `pik.bat` is run but not updated after a `pik refresh`. This means that if you've updated `PATH` after the initial run, `pik` will never use it and, other than manually editing `pik_run.bat`, it can't easily be changed.

I'd like to see `pik refresh` update both `config.yml` and `.pik\pik_run.bat` (haven't tested thing with PS yet)

Full disclosure...I ran into the above issue with the following setup so this could be a red herring and not applicable to normal use:

<pre><code>// desktop shortcut
Target: %COMSPEC% /Q /T:0E /E:ON /K C:\pik-test\pik_setup.bat

// file: c:\pik-test\pik_setup.bat
echo Configuring Pik testing environment...
set PIK_HOME=C:\pik-test\.pik
set PATH=%~dp0;%SystemRoot%\system32;%SystemRoot%;C:\ruby192\bin;C:\Python27\Scripts;C:\Python27;%GNUWIN%\curl\bin;C:\git\cmd;%GNUWIN%\less\bin;%GNUWIN%\grep\bin
</code></pre>

and running `echo %PATH%` (before and after `pik refresh`) from the above shortcut I get:

<pre><code>C:\Users\Jon\Documents>echo %PATH%
C:\pik-test\;C:\Windows\system32;C:\Windows;C:\ruby192\bin;C:\Python27\Scripts;C:\Python27;C:\gnuwin32\curl\bin;C:\git\cmd
</code></pre>

**Comment by vertiginous** [comment]
pik_run.bat should get overwritten every time `pik use` is called.  In fact it should get updated by any command that includes ScriptFileEditor.  Which means use, update, and system.  pik_run.bat should get deleted any other time pik_runner.exe is invoked.  If not, it's a bug.  I'll look into this.

**Comment by vertiginous** [comment]
Yes, pik_run.bat should get deleted every time pik is run.
https://github.com/vertiginous/pik/blob/master/lib/pik/commands/command.rb#L63

It should get recreated every time a command that relies on batch (or bash, or powershell, depending on the environment) files is run.

**Comment by jonforums** [comment]
Yes, `pik jruby-1.6.0` does update `pik_run.bat` but what appears to be happening in my case is that the updates don't matter because the original `PATH` set in my `pik_setup.bat` have been lost. I'm not sure this is really a use case you want to support though.

However, when I tried this from the shell opened from the shortcut it looks like the new PATH isn't being picked up if there's an intervening `pik ls`:

<pre><code>C:\Users\Jon\Documents>set PATH=%PATH%;%GNUWIN%\less\bin

C:\Users\Jon\Documents>echo %PATH%
C:\pik-test\;C:\Windows\system32;C:\Windows;C:\jruby\bin;C:\Python27\Scripts;C:\
Python27;C:\gnuwin32\curl\bin;C:\git\cmd;C:\gnuwin32\less\bin

C:\Users\Jon\Documents>pik ls
   ruby-1.8.7-p330
   ruby-1.9.2-p160
   ruby-1.9.3-dev
=> jruby-1.6.0

C:\Users\Jon\Documents>pik 1.9.2-p160

C:\Users\Jon\Documents>echo %PATH%
C:\pik-test\;C:\Windows\system32;C:\Windows;C:\ruby192\bin;C:\Python27\Scripts;C
:\Python27;C:\gnuwin32\curl\bin;C:\git\cmd
</code></pre>


Very strange because without the intervening `pik ls` the `PATH` appears to have been updated correctly.

**Comment by vertiginous** [comment]
Yeah, for some reason pik_run.bat isn't getting deleted like it should.  It gets overwritten, so pik use is working fine, but pik ls should not be changing your environment.  Good catch.

**Comment by vertiginous** [comment]
Fixed in 047058f5175cd5dcb7e3
