### ISSUE TITLE
pik list do not display the platform of the installed Rubies

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#98]
Hello,

From the following list:

<pre>
>pik ls
   ruby-1.8.6-p369
   ruby-1.8.6-p398
   ruby-1.8.7-p248
   ruby-1.8.7-p302
=> ruby-1.8.7-p330
   ruby-1.9.1-p376
   ruby-1.9.1-p430
   ruby-1.9.2-p136
   ruby-1.9.3-dev
   ironruby-1.0.0
   jruby-1.4.1
   jruby-1.5.2
</pre>

It is clear which one is JRuby and MRI, but is not clear which platfomr of ruby or jruby it is (could be mswin or mingw or could be 64bits jruby)

Will be great if the `[...]` part of the platform is displayed along the version:

<pre>
>pik ls

ruby-1.8.6-p398 [i386-mswin32]
</pre>

Thank you.

**Comment by vertiginous** [comment]
It would be hard to add the platform to that output without changing the way pik use works.  How about pik list --verbose.  Does that give you what you're looking for?

**Comment by luislavena** [comment]
Well, was thinking store the platform in another key of the config file, not as part of the version string.

But I can live with the current state ;-)

**Comment by vertiginous** [comment]
I just noticed 'rvm list' does show platform information.  This shouldn't be too hard to implement either.  I'll add it in soon.

**Comment by vertiginous** [comment]
Does this look right to you, Luis?

```
=> ruby-1.8.7-p249 [ i386-mingw32 ]
   ruby-1.8.7-p302 [ i386-mingw32 ]
   ruby-1.8.7-p330 [ i386-mingw32 ]
   ruby-1.9.1-p430 [ i386-mingw32 ]
   ruby-1.9.2-dev [ i386-mingw32 ]
   ruby-1.9.2-p0 [ i386-mingw32 ]
   ruby-1.9.2-p136 [ i386-mingw32 ]
   ironruby-1.1.0 [ .NET 4.0.30319.1 ]
   ironruby-1.1.1 [ .NET 4.0.30319.1 ]
   jruby-1.6.0 [ Windows 7-x86-java ]
   jruby-1.5.6 [ x86-java ]
```

**Comment by luislavena** [comment]
Yes, it does! Thank you!

**Comment by vertiginous** [comment]
closing.  Thanks, Luis.
